[package]
name = "emojibomb"
version = "0.1.0"
authors = ["xiwenli"]
edition = "2018"

[dependencies]
emojibomb_derive = { path = "./emojibomb_derive" }
rand = "*"
loglib = { package = "log", version = "*" , features = ["std"]}

[dev-dependencies]
