[package]
name = "simple_tcp_server"
version = "0.1.0"
authors = ["xiwenli"]
edition = "2018"

[dependencies]
emojibomb = { path = "../../emojibomb" }
tokio = { version = "*", features = ["rt-threaded", "net"] }